#====================================#
#========== PARAMS SETTING ==========#
[author]
name          = "Putra Jaya"
subtitle      = "🤖 Ngoding? Bisa. Paham? Nanti dulu. 🎨 CSS magician, tapi kadang kena kutukan sendiri. 🐛 Bug adalah sahabat, debugger adalah penyelamat."
logo          = "favicons/android-chrome-192x192.png"
twitter       = "@Masputrawae"
#====================================#
#============= GISCUS ===============#
[giscus]
    active                   = true
    data_repo                ="masputrawae/official"
    data_repo_id             ="R_kgDONFahNA"
    data_category            ="General"
    data_category_id         ="DIC_kwDONFahNM4CnBHb"
    data_mapping             ="pathname"
    data_strict              ="1"
    data_reactions_enabled   ="1"
    data_emit_metadata       ="1"
    data_input_position      ="bottom"

#====================================#
#========== WIDGET SETTING ==========#
[widget]
    pinned        = true
    recent_post   = true
    top_tags      = true
    top_categories= true

#====================================#
#=========== SOCIAL LINK ============#
[social]
[social.facebook]
    name = "Facebook"
    url  = "https://www.facebook.com/profile.php?id=61566134978045&mibextid=rS40aB7S9Ucbxw6v"
    icon = "bi-facebook"
[social.twitter]
    name = "TwitterX"
    url  = "https://x.com/Masputrawae"
    icon = "bi-twitter-x"
[social.instagram]
    name = "Instagram"
    url  = "https://www.instagram.com/masputrawae?igsh=MXZhNHBuY3ByYndjYg=="
    icon = "bi-instagram"
[social.github]
    name = "Github"
    url  = "https://github.com/masputrawae"
    icon = "bi-github"
[social.discord]
    name = "Discord"
    url  = "https://discord.gg/nM4EP8DJFZ"
    icon = "bi-discord"
